bins:
  - binary: sourcery 
    version: 
      requirement: "^2.0.0"
    installCommand: ["brew install sourcery", "gem install sourcery"]
  - binary: fastlane
    version:
      requirement: "^2.0.0"
      command: fastlane --version
      envVars: [FASTLANE_SKIP_UPDATE_CHECK=true]
    installCommand: ["gem install fastlane", "brew install fastlane"]