bins:
  - binary: sourcery 
    version: 
      requirement: "^2.0.0"
    installMethods:
      - command: "brew install sourcery"
  - binary: fastlane
    version:
      requirement: "^2.0.0"
      command: fastlane --version
      envVars: [FASTLANE_SKIP_UPDATE_CHECK=true]
    installMethods:
      - command: "gem install fastlane"
      - command: "brew install fastlane"
        updateCommand: "brew upgrade fastlane"