bins:
  - binary: sourcery 
    version: 
      requirement: "^2.0.0"
    installers: [brew]
  - binary: lefthook 
    version:
      requirement: "^0.7"
      command: "lefthook version"
    installers: [brew]
    postInstall:
      - command: "lefthook install"
  - binary: fastlane
    version:
      requirement: "^2.0.0"
      command: fastlane --version
      commandEnvVars: [FASTLANE_SKIP_UPDATE_CHECK=true]
    installers: [gem, brew]