name: Create git tag 

on:
  push:
    branches: [main, beta, alpha]

jobs:
  create-git-tag:
    name: Create git tag 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    

      - name: Create tag via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 19
          extra_plugins: |
            conventional-changelog-conventionalcommits@4
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@8
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}

      - name: Copy commits into develop after main deployment 
        uses: levibostian/action-sync-branches@v1
        with:
          behind: develop
          ahead: main 
          githubToken: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}