name: Deploy app 

# goreleaser requires git tags to build and deploy 
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the current version of Go from project.
        run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >>${GITHUB_ENV}
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Prepare for deployment 
        run: |
          docker login -u=levibostian -p="$DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}