name: Test

on: [push, pull_request]

jobs:
  test:
    name: Automated tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the current version of Go from project.
        run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >>${GITHUB_ENV}
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
          
      # goreleaser builds binary for many OSes. Good way to test that builds build successfully 
      - name: Test build & deployment 
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot --skip-publish # dry-run it 
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}  